"""
Example showing the functionality of data_handler using data generated by tweet_saver from helpers.
Run example_search.py first to receive your own example_search.txt.

"""

from helpers import Helpers


# initialize api
api_helpers = Helpers()

# Collect tweets from saved file
df = api_helpers.data_handler(tweets=None, geo=None, user_metadata=True, from_cursor=False,
                              filename="example_search.txt")
cleaned_df = api_helpers.clean_text_df(df)
print(cleaned_df)
